apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsocialmedia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appsocialmedia
  template:
    metadata:
      labels:
        app: appsocialmedia
    spec:
      volumes:
        - name: socialmediastorage
          persistentVolumeClaim:
            claimName: socialmediavolume
      containers:
        - name: appsocialmedia
          image: poornasrisrinu/appsocialmedia:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /app/data
              name: socialmediastorage
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appsocialmedia-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appsocialmedia
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: appsocialmedia-service
spec:
  selector:
    app: appsocialmedia
  ports:
    - name: http
      port: 5000
      nodePort: 30001
      targetPort: 5000
  type: LoadBalancer
